#!/usr/bin/env python3
"""One generator for every cross-language shape. Outputs are committed and
marked GENERATED, DO NOT EDIT. CI runs `gen.py --check` and fails on drift.

Usage: scripts/gen.py [--check]
"""

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests"))

CHECK = "--check" in sys.argv[1:]

HEADER_TS = "// GENERATED by scripts/gen.py. DO NOT EDIT. Source: reps/models.py.\n"


def zod_type(name, schema, defs):
    """Emit a Zod expression for one JSON-schema node. Returns source text."""
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1] + "Schema"
    if "const" in schema:
        return f"z.literal({json.dumps(schema['const'])})"
    if "enum" in schema:
        vals = ", ".join(json.dumps(v) for v in schema["enum"])
        return f"z.enum([{vals}])"
    if "anyOf" in schema:
        opts = schema["anyOf"]
        null = any(o.get("type") == "null" for o in opts)
        rest = [o for o in opts if o.get("type") != "null"]
        if len(rest) == 1:
            inner = zod_type(name, rest[0], defs)
            return f"{inner}.nullable()" if null else inner
        union = "z.union([" + ", ".join(zod_type(name, o, defs) for o in rest) + "])"
        return f"{union}.nullable()" if null else union
    t = schema.get("type")
    if t == "string":
        return "z.string()"
    if t == "integer":
        return "z.number().int()"
    if t == "number":
        return "z.number()"
    if t == "boolean":
        return "z.boolean()"
    if t == "null":
        return "z.null()"
    if t == "array":
        return f"z.array({zod_type(name, schema.get('items', {}), defs)})"
    if t == "object":
        props = schema.get("properties")
        if props is None:
            addl = schema.get("additionalProperties", True)
            if addl is True:
                return "z.record(z.string(), z.unknown())"
            return f"z.record(z.string(), {zod_type(name, addl, defs)})"
        req = set(schema.get("required", []))
        fields = []
        for k, v in props.items():
            expr = zod_type(k, v, defs)
            if k not in req:
                expr += ".optional()"
            fields.append(f"  {json.dumps(k)}: {expr},")
        strict = ".strict()" if schema.get("additionalProperties") is False else ""
        return "z.object({\n" + "\n".join(fields) + "\n})" + strict
    return "z.unknown()"


def zod_module(schema):
    defs = schema.get("$defs", {})
    parts = [HEADER_TS, 'import { z } from "zod";', ""]
    order = []
    # SnapshotModel references other defs; emit dependencies first via DFS.
    refs: dict[str, set[str]] = {}

    def collect(node, acc):
        if isinstance(node, dict):
            if "$ref" in node:
                acc.add(node["$ref"].split("/")[-1])
            for v in node.values():
                collect(v, acc)
        elif isinstance(node, list):
            for v in node:
                collect(v, acc)

    for k, v in defs.items():
        acc: set[str] = set()
        collect(v, acc)
        refs[k] = acc - {k}
    emitted: set[str] = set()

    def emit(k):
        if k in emitted:
            return
        for dep in sorted(refs.get(k, ())):
            if dep in defs:
                emit(dep)
        node = defs[k]
        if node.get("type") != "object" or "enum" in node or "$ref" in node or "anyOf" in node:
            parts.append(f"export const {k}Schema = {zod_type(k, node, defs)};")
        else:
            parts.append(f"export const {k}Schema = {zod_type(k, node, defs)};")
        parts.append("")
        emitted.add(k)
        order.append(k)

    for k in defs:
        emit(k)
    root = {k: v for k, v in schema.items() if k != "$defs"}
    parts.append(f"export const snapshotSchema = {zod_type('snapshot', root, defs)};")
    parts.append("export type Snapshot = z.infer<typeof snapshotSchema>;")
    for k in order:
        if k == "SnapshotModel":
            continue
        parts.append(f"export type {k} = z.infer<typeof {k}Schema>;")
    parts.append("")
    return "\n".join(parts)


def write(path, content):
    path = ROOT / path
    if CHECK:
        if not path.exists() or path.read_text() != content:
            print(f"gen: drift in {path.relative_to(ROOT)} (run scripts/gen.py)")
            global DRIFT
            DRIFT = True
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"gen: wrote {path.relative_to(ROOT)}")


DRIFT = False

# Fixtures must be byte-stable: every "today" read during generation is
# frozen, so regenerating on a later day yields identical files and
# `gen.py --check` stays green in CI.
FROZEN_TODAY = (2026, 9, 24)
FROZEN_NOW = "2026-09-24T12:00:00"


def _freeze_time():
    import datetime as _dt
    import sys

    class FrozenDate(_dt.date):
        @classmethod
        def today(cls):
            return cls(*FROZEN_TODAY)

    class FrozenDateTime(_dt.datetime):
        @classmethod
        def now(cls, tz=None):
            return cls(2026, 9, 24, 12, 0, 0)

    for name, mod in list(sys.modules.items()):
        if not (name == "scenarios" or name.startswith("reps.")):
            continue
        if getattr(mod, "date", None) is _dt.date:
            mod.date = FrozenDate
        if getattr(mod, "datetime", None) is _dt.datetime:
            mod.datetime = FrozenDateTime


def main():
    global DRIFT
    from reps.db import SCHEMA_VERSION
    from reps.models import ConstantsModel, SnapshotModel

    snap_schema = SnapshotModel.model_json_schema()
    const_schema = ConstantsModel.model_json_schema()
    write("schema/snapshot.schema.json", json.dumps(snap_schema, indent=2) + "\n")
    write("schema/constants.schema.json", json.dumps(const_schema, indent=2) + "\n")
    write("dashboard/src/generated/snapshot.ts", zod_module(snap_schema))
    from reps.models import SNAPSHOT_SCHEMA_VERSION as SNAP_VER
    write("dashboard/src/generated/version.ts",
          HEADER_TS + f"export const SCHEMA_VERSION = {SCHEMA_VERSION};\n"
          + f"export const SNAPSHOT_SCHEMA_VERSION = {SNAP_VER};\n")

    # Blank: a valid v2 snapshot of an empty DB (the worker's no-sync payload).
    import sqlite3
    import tempfile
    from reps import db as _db
    from reps.snapshot import build_views
    import scenarios
    _freeze_time()
    fd, tmp = tempfile.mkstemp(suffix=".db")
    os.close(fd)
    url = _db.DB
    try:
        _db.DB = tmp
        c = _db.conn()
        blank = build_views(c)
        c.close()
    finally:
        _db.DB = url
        os.unlink(tmp)
    from reps.models import validate_snapshot
    validate_snapshot(blank)
    write("dashboard/src/generated/blank.json", json.dumps(blank, indent=2) + "\n")

    # Fixtures from real backend scenarios (module already loaded above so the
    # freeze patches its date reference too).
    for name, seed in scenarios.SCENARIOS.items():
        fd, tmp = tempfile.mkstemp(suffix=".db")
        os.close(fd)
        try:
            _db.DB = tmp
            import reps as _reps
            c = _reps.conn()
            seed(_reps)
            snap = _reps.export_snapshot()
            payload = json.dumps(snap, indent=2) + "\n"
        finally:
            _db.DB = url
            os.unlink(tmp)
        write(f"dashboard/e2e/fixtures/{name}.json", payload)
        write(f"dashboard/src/__tests__/fixtures/{name}.json", payload)

    # Doc value markers (sync_docs.py owns the fill; --check diffs here too).
    import subprocess
    if CHECK:
        r = subprocess.run([sys.executable, "scripts/sync_docs.py", "--check"],
                           capture_output=True, text=True, cwd=ROOT)
        if r.returncode != 0:
            print(r.stdout.strip())
            DRIFT = True
    else:
        subprocess.run([sys.executable, "scripts/sync_docs.py"], check=True, cwd=ROOT)

    if CHECK and DRIFT:
        print("gen: generated files differ, run scripts/gen.py and commit")
        return 1
    if not CHECK:
        print("gen: all outputs current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
